name: Test Package
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
      - run: npm install
      - run: npm run data || true
      - run: npm run datalog || true
      - run: npm run test
      - name: Push test result to Testspace
        run: |
          testspace [${{ matrix.os}}/node-${{ matrix.node-version}}]xunit.xml
        if: always()