name: Test Package
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
      - run: npm install
      - run: npm run data || true
      - run: npm run test
      - name: Push test result to Testspace
        run: |
          testspace [${{ matrix.os}}]cypress/results/results.test*
        if: always()